# autogenerated by txs
#include:auxhook
#include:iftex
\csname#S
\noexpand#S
\texttransparent{arg1}{arg2}#S
\transparent{arg1}#S
\x#S
\__hook auxhook#S
\__hook iftex#S
\unprocessedoptions-auxhook.sty#S
\unprocessedoptions-iftex.sty#S
auxhook.sty#S
csnameendcsname#S
iftex.sty#S
