#!/bin/bash

process_exists() { [[ ! $(pidof "$@") ]]; }

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d I II III IV V 
bspc monitor LVDS-1 -d VI VII VIII IX X

unfocused=#3D4150
focused=#5294E2
select=#4D586E

bspc config border_width          2
bspc config window_gap            12
bspc config normal_border_color   "$unfocused"
bspc config active_border_color   "$select"
bspc config focused_border_color  "$focused"
bspc config presel_feedback_color "$select"

bspc config borderless_monocle    true
bspc config focus_follows_pointer true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        true
bspc config split_ratio           0.52

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# Other config
#

setxkbmap -option grp:win_space_toggle

synclient TapButton1=1 \
          CoastingSpeed=0

#
# Startup
#

function start() {
    case $1 in 
        -s|--sleep|[)
            sleep $2
            shift 3
            ;;
    esac

}

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

autorandr quarto &
(sleep 2s; nitrogen --restore) &
dunst &
picom &

(sleep 5s; conky) &

redshift &
xfce4-power-manager &
xfce4-volumed-pulse &
thunar --daemon &

fucking-razer.sh
evrouter /dev/input/by-id/usb-Razer_Razer_* &

